#!/usr/bin/python3

import socket
import argparse
import subprocess

def readargs():
   parser = argparse.ArgumentParser(description='udp')

   #parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', help='show more verbose output where applicable')
   parser.add_argument('-p', '--port', dest='port', type=int, nargs='?', required = True, help='udp port to listen on')
   parser.add_argument('-c', '--command', dest='command', type=str, nargs='?', required = True, help='command to run to generate output')
   return parser

def main():
   parser = readargs()
   args = parser.parse_args()

   try:
      cmdoutput = subprocess.check_output(args.command, shell=True, text=True)
   except subprocess.CalledProcessError as e:
      print(f"Error executing command: {e}")
      exit(1)

   sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
   sock.bind(('', args.port))

   while True:
       data, addr = sock.recvfrom(1024)
       sock.sendto(bytes(cmdoutput, "utf-8"),addr)

if __name__ == "__main__":
    main()
